import { createFileRoute } from "@tanstack/react-router";
import { Check, Mail, MapPin, Phone } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { StatCounter } from "@/components/stat-counter";
import { stats } from "@/lib/site-data";

export const Route = createFileRoute("/about")({ head:()=>({meta:[{title:"About Us | the trash co."},{name:"description",content:"Meet the circular economy specialists behind the trash co.'s EPR compliance and materials work across India."},{property:"og:title",content:"About the trash co."},{property:"og:description",content:"Building a transparent, tech-enabled circular economy for Indian business."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: AboutPage });
const values=["Customer Excellence","Integrity","Trust","Reliability","Transparency"];
const roles=["Co-Founder & Strategy","Co-Founder & Operations","Head — Compliance","Head — Operations","Business Development Manager","Head — Marketing","Compliance Executive","Compliance Executive","Admin Assistant"];
function AboutPage(){return <main><PageHero eyebrow="About us" title="A circular economy needs clear connections." copy="We connect businesses, regulation, recyclers and high-quality materials through a system built around transparency, trust and trash." />
<section className="section-pad"><div className="site-container grid gap-14 lg:grid-cols-2"><Reveal><SectionHeading eyebrow="Our mission" title="Enabling a Circular Economy." /></Reveal><Reveal delay={100}><p className="text-xl leading-9 text-muted-foreground">We are paving the way for a sustainable future by building a <strong className="text-foreground">Tech-Enabled Circular Economy</strong>—helping clients meet obligations while unlocking revenue potential from their waste streams.</p><p className="mt-6 leading-7 text-muted-foreground">Our work spans compliance strategy, traceable waste channelisation, documentation and recycled polymer supply. The result is one accountable partner across a complex chain.</p></Reveal></div><div className="mt-20 grid grid-cols-2 gap-6 lg:grid-cols-4">{stats.map(s=><StatCounter key={s.label} {...s}/>)}</div></section>
<section className="section-pad bg-light-muted"><div className="site-container"><SectionHeading eyebrow="How we work" title="Five values. One operating standard." /><div className="mt-14 grid gap-px bg-light-border sm:grid-cols-2 lg:grid-cols-5">{values.map((v,i)=><Reveal key={v} delay={i*60} className="bg-light-surface p-7"><span className="grid size-8 place-items-center rounded-full bg-primary"><Check className="size-4" /></span><h3 className="mt-20 font-display text-xl font-bold">{v}</h3></Reveal>)}</div></div></section>
<section className="section-pad bg-dark text-dark-foreground"><div className="site-container"><SectionHeading inverse eyebrow="Our team" title="Specialists who keep the circle moving." copy="A cross-functional team working across strategy, compliance, operations, business development and client support."/><p className="mt-5 text-xs text-dark-muted">Team names, direct emails and phone numbers can be added when supplied.</p><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roles.map((role,i)=><Reveal key={role} delay={(i%3)*50} className="group border border-dark-foreground/15 p-6"><div className="grid aspect-[4/3] place-items-center bg-dark-foreground/[0.04]"><div className="grid size-24 place-items-center rounded-full border border-primary/60 font-display text-2xl font-bold text-primary">TC</div></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-primary">Team member</p><h3 className="mt-2 font-display text-xl font-bold">{role}</h3><div className="mt-5 flex gap-2 text-dark-muted"><Mail className="size-4"/><Phone className="size-4"/></div></Reveal>)}</div></div></section>
<section className="section-pad"><div className="site-container grid gap-8 md:grid-cols-2"><div className="border-l-4 border-primary p-8"><MapPin className="size-6 text-primary-dark"/><h2 className="mt-7 font-display text-3xl font-bold">Panaji, Goa</h2><p className="mt-2 text-muted-foreground">Registered office</p></div><div className="border-l-4 border-primary p-8"><MapPin className="size-6 text-primary-dark"/><h2 className="mt-7 font-display text-3xl font-bold">Ahmedabad, Gujarat</h2><p className="mt-2 text-muted-foreground">Registered office</p></div></div></section></main>}