import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { CheckCircle2, Mail, MapPin, Phone } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/contact")({head:()=>({meta:[{title:"Contact | the trash co."},{name:"description",content:"Talk to the trash co. about EPR compliance, waste management or recycled polymer requirements in India."},{property:"og:title",content:"Contact the trash co."},{property:"og:description",content:"Start a conversation about compliance or recycled materials."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ContactPage});
function ContactPage(){const [sent,setSent]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(e.currentTarget.checkValidity()){setSent(true);e.currentTarget.reset();}}return <main><PageHero eyebrow="Contact" title="Let’s turn responsibility into momentum." copy="Tell us where your compliance or materials challenge stands. Our team will help define the next practical step."/><section className="section-pad"><div className="site-container grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><h2 className="font-display text-3xl font-bold">Talk directly</h2><div className="mt-8 space-y-4"><a href="mailto:hello@thetrash.company" className="flex items-center gap-4 border-b border-light-border pb-4"><Mail className="size-5 text-primary-dark"/><span>hello@thetrash.company</span></a><a href="mailto:team@thetrash.company" className="flex items-center gap-4 border-b border-light-border pb-4"><Mail className="size-5 text-primary-dark"/><span>team@thetrash.company</span></a><a href="tel:+918275073790" className="flex items-center gap-4 border-b border-light-border pb-4"><Phone className="size-5 text-primary-dark"/><span>+91 82750 73790</span></a></div><div className="mt-10 flex gap-4"><MapPin className="size-5 shrink-0 text-primary-dark"/><p className="text-sm leading-6 text-muted-foreground">Registered offices<br/><strong className="text-foreground">Panaji, Goa</strong><br/><strong className="text-foreground">Ahmedabad, Gujarat</strong></p></div></div><div className="border border-light-border bg-light-surface p-6 sm:p-9"><h2 className="font-display text-3xl font-bold">Start a conversation</h2>{sent?<div role="status" className="mt-10 border-l-4 border-primary bg-light-muted p-6"><CheckCircle2 className="size-8 text-primary-dark"/><p className="mt-4 font-display text-xl font-bold">Thank you. Your enquiry is ready.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">This preview confirms the form locally. Connect an email service before launch to deliver submissions to the team.</p><Button className="mt-5" variant="outline" onClick={()=>setSent(false)}>Send another</Button></div>:<form className="mt-8 grid gap-5 sm:grid-cols-2" onSubmit={submit}><Field label="Name"><Input required name="name" autoComplete="name"/></Field><Field label="Contact number"><Input required name="phone" inputMode="tel" pattern="[0-9+() -]{8,18}" autoComplete="tel"/></Field><Field label="Email"><Input required type="email" name="email" autoComplete="email"/></Field><Field label="Company name"><Input required name="company" autoComplete="organization"/></Field><Field label="Message" full><Textarea required name="message" rows={6} className="min-h-36"/></Field><div className="sm:col-span-2"><Button type="submit" size="xl">Send enquiry</Button></div></form>}</div></div></section></main>}
function Field({label,children,full=false}:{label:string;children:React.ReactNode;full?:boolean}){return <label className={full?"sm:col-span-2":""}><span className="mb-2 block text-sm font-bold">{label}</span>{children}</label>}