import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Asterisk, Quote, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { StatCounter } from "@/components/stat-counter";
import { clients, services, stats, testimonials } from "@/lib/site-data";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "the trash co. | EPR Compliance & Circular Economy India" },
    { name: "description", content: "Tech-enabled EPR compliance, waste channelisation and recycled polymer solutions across India." },
    { property: "og:title", content: "the trash co. | Enabling a Circular Economy" },
    { property: "og:description", content: "Transparent EPR compliance and high-grade recycled polymers for businesses across India." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: HomePage,
});

function HomePage() {
  return <main>
    <section className="grid-lines relative min-h-[760px] overflow-hidden bg-dark pb-20 pt-32 text-dark-foreground sm:min-h-[820px]">
      <div className="site-container relative z-10 grid items-end gap-12 pt-10 lg:grid-cols-[1fr_420px] lg:pt-20">
        <Reveal><p className="mb-7 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-primary"><Asterisk className="size-4" /> India’s circular economy partner</p><h1 className="font-display text-[clamp(3.4rem,9vw,8.5rem)] font-extrabold leading-[0.78] tracking-normal"><span className="block">Transparency.</span><span className="block text-primary">Trust.</span><span className="block">Trash.</span></h1><p className="mt-10 max-w-xl text-lg leading-8 text-dark-muted">We connect regulation, recovery and recycled materials to make circularity work for Indian business.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="xl" variant="hero"><Link to="/services">Explore EPR solutions <ArrowRight /></Link></Button><Button asChild size="xl" variant="light"><Link to="/recycled-polymers">Source recycled polymers</Link></Button></div></Reveal>
        <Reveal delay={160} className="relative hidden h-[430px] lg:block"><div className="absolute inset-4 rounded-full border border-dark-foreground/20" /><div className="absolute inset-16 animate-[orbit_22s_linear_infinite] rounded-full border-2 border-dashed border-primary/70"><span className="absolute -top-3 left-1/2 size-6 rounded-full bg-primary" /><span className="absolute bottom-6 right-6 size-3 rounded-full bg-earth" /></div><div className="absolute inset-28 grid place-items-center rounded-full bg-dark-foreground text-center text-dark"><div><RecycleMark /><p className="mt-3 text-xs font-bold uppercase tracking-[0.16em]">Enabling a<br />circular economy</p></div></div></Reveal>
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-px bg-dark-foreground/10" />
    </section>

    <section className="section-pad bg-background"><div className="site-container"><Reveal><div className="grid gap-10 lg:grid-cols-[1fr_1.2fr]"><SectionHeading eyebrow="Impact in motion" title="Waste is not the end of the line." /><p className="max-w-xl self-end text-xl leading-8 text-muted-foreground">It is a measurable material stream, a compliance responsibility and—managed well—a source of value. We build the systems that connect all three.</p></div></Reveal><div className="mt-16 grid grid-cols-2 gap-x-6 gap-y-10 lg:grid-cols-4">{stats.map((stat) => <StatCounter key={stat.label} {...stat} />)}</div></div></section>

    <section className="section-pad bg-dark text-dark-foreground"><div className="site-container"><Reveal><SectionHeading inverse eyebrow="Compliance, made actionable" title="One partner across the EPR landscape." copy="From registration to credit fulfilment and audit-ready documentation, we turn regulation into a clear operating system." /></Reveal><div className="mt-14 grid auto-rows-[250px] grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">{services.map((service, index) => { const Icon=service.icon; return <Reveal key={service.title} delay={index*60} className={index===0 || index===5 ? "lg:col-span-2" : ""}><Link to="/services" className="group relative flex h-full flex-col overflow-hidden border border-dark-foreground/15 bg-dark-foreground/[0.035] p-6 transition-all hover:border-primary/70 hover:bg-dark-foreground/[0.07]"><span className="mb-auto grid size-11 place-items-center rounded-full border border-dark-foreground/20 text-primary"><Icon className="size-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-dark-muted">0{index+1}</p><h3 className="mt-2 font-display text-2xl font-bold">{service.title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-dark-muted opacity-80 transition-opacity group-hover:opacity-100">{service.description}</p></div><ArrowRight className="absolute right-5 top-5 size-5 transition-transform group-hover:translate-x-1" /></Link></Reveal>})}</div></div></section>

    <section className="section-pad bg-light-surface"><div className="site-container grid gap-12 lg:grid-cols-[1fr_1fr]"><Reveal><SectionHeading eyebrow="Materials, recirculated" title="High-grade PCR polymers with a clear second life." copy="Reliable recycled feedstock for packaging, automotive and consumer applications—sourced with quality and compliance in view." /><Button asChild variant="ink" size="xl" className="mt-8"><Link to="/recycled-polymers">Explore polymer grades <ArrowRight /></Link></Button></Reveal><Reveal delay={120} className="grid grid-cols-2 gap-3"><div className="bg-primary p-6 sm:p-8"><p className="font-display text-5xl font-bold">04</p><p className="mt-16 text-sm font-bold uppercase tracking-[0.14em]">Core material grades</p></div><div className="border border-light-border p-6 sm:p-8"><p className="text-sm text-muted-foreground">Applications</p><p className="mt-6 font-display text-2xl font-bold">Rigid + Flexible Packaging</p></div><div className="col-span-2 border border-light-border p-6 sm:p-8"><p className="text-sm text-muted-foreground">Also engineered for</p><div className="mt-5 flex flex-wrap gap-2">{["Automotive components","Consumer goods","Caps & closures"].map(x=><span key={x} className="border border-light-border px-3 py-2 text-sm">{x}</span>)}</div></div></Reveal></div></section>

    <section className="section-pad bg-background"><div className="site-container"><Reveal><SectionHeading eyebrow="Trusted relationships" title="Compliance feels simpler with the right team." /></Reveal><p className="mt-5 text-xs text-muted-foreground">Representative client feedback, paraphrased for clarity.</p><div className="mt-12 grid gap-3 lg:grid-cols-5">{testimonials.map((item,index)=><Reveal key={item.company} delay={index*50} className="border border-light-border bg-light-surface p-6"><div className="flex gap-0.5 text-primary-dark" aria-label="5 out of 5 stars">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-3 fill-current" />)}</div><Quote className="mt-8 size-7 text-primary" /><blockquote className="mt-4 text-sm leading-6">“{item.quote}”</blockquote><p className="mt-7 border-t border-light-border pt-4 text-xs font-bold uppercase tracking-[0.1em]">{item.company}</p></Reveal>)}</div></div></section>

    <section className="overflow-hidden border-y border-light-border bg-light-muted py-9"><p className="mb-6 text-center text-xs font-bold uppercase tracking-[0.18em] text-muted-foreground">Companies across sectors have worked with our team</p><div className="marquee-track flex gap-3">{[...clients,...clients].map((client,index)=><div key={`${client}-${index}`} className="flex h-18 w-56 shrink-0 items-center justify-center border border-light-border bg-light-surface px-5 text-center font-display text-sm font-bold">{client}</div>)}</div></section>

    <section className="section-pad bg-primary text-primary-foreground"><div className="site-container flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em]">Start with clarity</p><h2 className="mt-5 max-w-4xl font-display text-5xl font-bold leading-[0.95] sm:text-7xl">Turn your obligations into forward motion.</h2></div><Button asChild size="xl" variant="ink"><Link to="/contact">Talk to our team <ArrowRight /></Link></Button></div></section>
  </main>;
}

function RecycleMark() { return <svg viewBox="0 0 100 100" className="mx-auto size-24" aria-hidden="true"><path d="M50 12a38 38 0 1 1-27 11" fill="none" stroke="currentColor" strokeWidth="8" strokeLinecap="round"/><path d="M12 13h22L23 33z" fill="currentColor"/><circle cx="50" cy="50" r="5" fill="var(--color-primary)"/></svg>; }