import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { Button } from "@/components/ui/button";
import { polymers, support } from "@/lib/site-data";
import ldpe from "@/assets/recycled-ldpe.jpg"; import hdpe from "@/assets/recycled-hdpe.jpg"; import raffia from "@/assets/recycled-pp-raffia.jpg"; import ppcp from "@/assets/recycled-ppcp.jpg";
const images=[ldpe,hdpe,raffia,ppcp];
export const Route=createFileRoute("/recycled-polymers")({head:()=>({meta:[{title:"Recycled PCR Polymers India | the trash co."},{name:"description",content:"Source high-grade r.LDPE, r.HDPE, PP Raffia and PPCP recycled polymers for packaging, automotive and consumer applications."},{property:"og:title",content:"High-Grade Recycled Polymers | the trash co."},{property:"og:description",content:"Reliable PCR polymer sourcing with quality assurance and packaging development support."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:PolymerPage});
function PolymerPage(){return <main><PageHero eyebrow="Recycled polymers" title="Better material. Clearer provenance." copy="High-grade post-consumer recycled polymers for manufacturers ready to make recycled content a reliable part of production."/>
<section className="section-pad"><div className="site-container"><SectionHeading eyebrow="PCR portfolio" title="Four grades. Many second lives."/><div className="mt-14 grid gap-3 md:grid-cols-2">{polymers.map((p,i)=><Reveal key={p.name} delay={i*60}><article className="group overflow-hidden border border-light-border bg-light-surface"><div className="aspect-[4/3] overflow-hidden"><img src={images[i]} alt={`${p.name} recycled polymer granules and example application`} width={1200} height={900} loading="lazy" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary-dark">{p.note}</p><h2 className="mt-2 font-display text-3xl font-bold">{p.name}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.applications}</p></div></article></Reveal>)}</div></div></section>
<section className="section-pad bg-light-muted"><div className="site-container"><SectionHeading eyebrow="Recycled-content obligations" title="ERP Rules for Recycled Plastic Granules" copy="Plastic Waste Management Amendment Rules, 2022 — minimum recycled plastic content indicated as percentages for PIBOs."/><div className="mt-12 overflow-x-auto border border-light-border bg-light-surface"><table className="w-full min-w-[680px] border-collapse text-left"><caption className="sr-only">Recycled content percentage schedule by plastic packaging category</caption><thead><tr className="bg-dark text-dark-foreground"><th className="p-5">Category</th><th className="p-5">2025–26</th><th className="p-5">2026–27</th><th className="p-5">2027–28</th><th className="p-5">2028 onwards</th></tr></thead><tbody>{[["Cat I","30","40","50","60"],["Cat II","10","10","20","20"],["Cat III","05","05","10","10"]].map(row=><tr key={row[0]} className="border-t border-light-border">{row.map((cell,i)=><td key={cell} className={`p-5 ${i===0?"font-bold":"font-display text-2xl"}`}>{cell}{i>0?<span className="text-sm">%</span>:null}</td>)}</tr>)}</tbody></table></div></div></section>
<section className="section-pad bg-dark text-dark-foreground"><div className="site-container"><SectionHeading inverse eyebrow="How we help" title="Confidence from source to shelf."/><div className="mt-12 grid gap-px bg-dark-foreground/15 sm:grid-cols-2 lg:grid-cols-4">{support.map((s,i)=>{const Icon=s.icon;return <Reveal key={s.title} delay={i*50} className="bg-dark p-7"><Icon className="size-7 text-primary"/><h3 className="mt-16 font-display text-xl font-bold">{s.title}</h3></Reveal>})}</div><div className="mt-14 flex flex-wrap gap-2">{["Rigid Packaging","Flexible Packaging","Automotive Components","Consumer Goods","Caps & Closures"].map(x=><span key={x} className="border border-dark-foreground/20 px-4 py-3 text-sm text-dark-muted">{x}</span>)}</div><Button asChild variant="hero" size="xl" className="mt-10"><Link to="/contact">Request a material conversation <ArrowRight/></Link></Button></div></section></main>}