import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { Button } from "@/components/ui/button";
import { services } from "@/lib/site-data";

export const Route=createFileRoute("/services")({head:()=>({meta:[{title:"EPR Compliance Services India | the trash co."},{name:"description",content:"End-to-end Plastic, Battery, E-Waste and Tyre EPR compliance, credits, waste management and environmental services."},{property:"og:title",content:"EPR Compliance Services | the trash co."},{property:"og:description",content:"Practical, transparent compliance support across India's EPR categories."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ServicesPage});
function ServicesPage(){return <main><PageHero eyebrow="EPR & environmental services" title="Compliance that works in the real world." copy="A practical operating partner for producers, importers and brand owners navigating India's evolving environmental regulations." />
<section className="section-pad"><div className="site-container"><SectionHeading eyebrow="EPR categories" title="From obligation to evidence." copy="We coordinate each stage—from applicability and registration through fulfilment, filing and audit support."/><div className="mt-14 grid auto-rows-[280px] gap-3 md:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=>{const Icon=s.icon;return <Reveal key={s.title} delay={i*50} className={i===0?"md:col-span-2":i===5?"lg:col-span-2":""}><article className="group flex h-full flex-col border border-light-border bg-light-surface p-7 transition-all hover:border-primary-dark"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-full bg-primary"><Icon className="size-5"/></span><span className="text-xs text-muted-foreground">0{i+1}</span></div><div className="mt-auto"><h2 className="font-display text-2xl font-bold">{s.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{s.description}</p></div></article></Reveal>})}</div></div></section>
<section className="section-pad bg-dark text-dark-foreground"><div className="site-container grid gap-14 lg:grid-cols-2"><SectionHeading inverse eyebrow="Beyond EPR" title="Environmental systems, joined up." copy="Additional support for environmental services, waste management and other compliances—designed around your actual operations."/><div className="grid gap-3">{["Applicability and gap assessment","Registrations and authorisations","Waste collection and channelisation","Returns, documentation and audit readiness","Credit strategy and procurement"].map((x,i)=><Reveal key={x} delay={i*40} className="flex items-center gap-4 border-b border-dark-foreground/15 py-5"><CheckCircle2 className="size-5 text-primary"/><span className="font-display text-lg font-bold">{x}</span></Reveal>)}</div></div></section>
<section className="section-pad bg-primary"><div className="site-container flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em]">Your next filing starts here</p><h2 className="mt-5 max-w-3xl font-display text-5xl font-bold leading-none">Build a cleaner compliance path.</h2></div><Button asChild variant="ink" size="xl"><Link to="/contact">Discuss your obligations <ArrowRight/></Link></Button></div></section></main>}